/*Tabla Alumnos*/
	TRUNCATE alumnos; ## reiniciamos la tabla Alumnos
	INSERT INTO alumnos(nombre, apellido)
	VALUES	('Abel',''),
			('Ace',''),
			('Adon',''),
			('Akuma',''),
			('Alex',''),
			('Area',''),
			('Balrog',''),
			('Blair','Dame'),
			('Blanka',''),
			('C.','Viper'),
			('Cammy',''),
			('Charlie','Nash'),
			('Chun-Li',''),
			('Dan','Hibiki'),
			('Darun',''),
			('Decapre',''),
			('Dee','Jay'),
			('Dhalsim',''),
			('Doctrine','Dark'),
			('Dudley',''),
			('Eagle',''),
			('Edmond','Honda'),
			('El Fuerte',''),
			('Elena',''),
			('Eliza','Masters'),
			('Fei','Long'),
			('Geki',''),
			('Gen',''),
			('Gill',''),
			('Gou','Hibiki'),
			('Gouken',''),
			('Guile',''),
			('Guy',''),
			('Hakan',''),
			('Hayate',''),
			('Hugo','Andore'),
			('Ibuki',''),
			('Ingrid',''),
			('Juli',''),
			('Juni',''),
			('Juri','Han'),
			('Kairi',''),
			('Karin','Kanzuki'),
			('Ken','Masters'),
			('Lee',''),
			('M','Bison'),
			('Maki','Genryusai'),
			('Makoto',''),
			('Mike',''),
			('Necro',''),
			('Oro',''),
			('Poison',''),
			('Rainbow','Mika'),
			('Remy',''),
			('Rolento','Schugerg'),
			('Rose',''),
			('Rufus',''),
			('Ryu',''),
			('Sagat',''),
			('Sakura','Kasugano'),
			('Sawada',''),
			('Sean','Matsuda'),
			('Seth','SFIV'),
			('Sharon',''),
			('Hawk','Thunder'),
			('Toro',''),
			('Cody','Travers'),
			('Twelve',''),
			('Urien',''),
			('Vega',''),
			('Rosso','Vulcano'),
			('Yang',''),
			('Yun',''),
			('Zangief','');
	SELECT * FROM alumnos;
    UPDATE alumnos 
    SET correo=CONCAT(alumnos.nombre,alumnos.apellido,'@gmail.com');