DROP DATABASE IF EXIStS SALUDOS;
CREATE DATABASE saludos;
USE SALUDOS;

CREATE TABLE mensajes(
	id_mensaje INT AUTO_INCREMENT,
    mensaje VARCHAR(50),
    PRIMARY KEY(id_mensaje),
    UNIQUE KEY(mensaje)
);

INSERT INTO mensajes(mensaje)
	VALUES
		('buenos dias'),
        ('¿como estan?'),
        ('hasta la proxima'),
        ('exito con sus proyectos');
        
CREATE TABLE ALUMNOS(
	ID_ALUMNO INT AUTO_INCREMENT,
    APELLIDO VARCHAR(50),
    NOMBRE VARCHAR(50),
    DOCUMENTO INT NOT NULL,
    PRIMARY KEY(ID_ALUMNO),
    UNIQUE KEY(APELLIDO, NOMBRE, DOCUMENTO)
);

CREATE TABLE COMUNICACIONES(
	ID_COMUNICACION INT AUTO_INCREMENT,
    ALUMNO INT,
    MENSAJE INT,
	PRIMARY KEY(ID_COMUNICACION),
    FOREIGN KEY(ALUMNO) REFERENCES ALUMNOS(ID_ALUMNO),
    FOREIGN KEY(ALUMNO) REFERENCES MENSAJES(ID_MENSAJE)
);