[Interface]
PrivateKey = kJJJ8gfFJYRiYvUUxEOqvzUqw/fK9HuNnjTY9lMMp20=
Address = 10.0.0.2/27

[Peer]
PublicKey = n3POQyF8uQp5qT5ycnTZqDfbZ4or+VNQWpzOnh+4Eiw=
EndPoint = 192.168.0.251:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepAlive = 10
