[Interface]
PrivateKey = MOReMi/xeDw5LNDqzW6mydd3w6xdKu++20TaYQwlD2g=
Address = 10.0.0.2/27
DNS = 8.8.8.8

[Peer]
PublicKey = sFM2RzbSUCq4ngBVJRXM+6sloPQbPHkpyXX3GuC0ehc=
Endpoint = 192.168.0.64:51820
AllowedIPs = 0.0.0.0/0
