[Interface]
PrivateKey = KODNj5dBGRsbTSnogdvnPx0RXSsjo+KJz8Wx2bHxEks=
Address = 10.0.0.2/27

[Peer]
PublicKey = QCk5CehY6enQ/JPgfs7y61YTnBXgbQJ9NYelAAFhw04=
EndPoint = 192.168.0.217:51820
AllowedIPs = 0.0.0.0/0
